on:
  release:
    types: [created]
  push:

jobs:
  release:
    name: Release binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: --path . --root .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/umaximize.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
